# Problem Statement

Chrun prediction of e-commerce customers

# Data Gathering

In [2]:
from warnings import filterwarnings
filterwarnings('ignore')

In [3]:
import os
os.chdir('D:/Dataset/')

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv('e_commerce.csv')
df

,account length,location code,user id,credit card info save,push status,add to wishlist,desktop sessions,app sessions,desktop transactions,total product detail views,session duration,promotion clicks,avg order value,sale product views,discount rate per visited products,product detail view per app session,app transactions,add to cart per session,customer service calls,churn
0,128,415,3824657,no,yes,25,265,45,17,110.0,197,87,244.7,91,11.01,10.0,3,2.70,1.0,0
1,107,415,3717191,no,yes,26,162,27,17,123.0,196,103,254.4,103,11.45,13.7,3,3.70,1.0,0
2,137,415,3581921,no,no,0,243,41,10,114.0,121,110,162.6,104,7.32,12.2,5,3.29,0.0,0
3,84,408,3759999,yes,no,0,299,51,5,71.0,62,88,196.9,89,8.86,6.6,7,1.78,2.0,0
4,75,415,3306626,yes,no,0,167,28,13,113.0,148,122,186.9,121,8.41,10.1,3,2.73,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,192,415,4144276,no,yes,36,156,27,18,77.0,216,126,279.1,83,12.56,9.9,6,2.67,2.0,0
3329,68,415,3703271,no,no,0,231,39,13,NaN,153,55,191.3,123,8.61,9.6,4,2.59,3.0,0
3330,28,510,3288230,no,no,0,181,31,25,109.0,289,58,191.9,91,8.64,14.1,6,3.81,2.0,0
3331,184,510,3646381,yes,no,0,214,36,14,105.0,160,84,139.2,137,6.26,5.0,10,1.35,2.0,0
3332,74,415,4004344,no,yes,25,234,40,23,113.0,266,82,241.4,77,10.86,13.7,4,3.70,0.0,0

# EDA

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   account length                       3333 non-null   int64
 1   location code                        3333 non-null   int64
 2   user id                              3333 non-null   int64
 3   credit card info save                3333 non-null   object
 4   push status                          3333 non-null   object
 5   add to wishlist                      3333 non-null   int64
 6   desktop sessions                     3333 non-null   int64
 7   app sessions                         3333 non-null   int64
 8   desktop transactions                 3333 non-null   int64
 9   total product detail views           3281 non-null   float64
 10  session duration                     3333 non-null   int64
 11  promotion clicks                     3333 non-null   int64
 12  avg order value                      3333 non-null   float64
 13  sale product views                   3333 non-null   int64
 14  discount rate per visited products   3333 non-null   float64
 15  product detail view per app session  3272 non-null   float64
 16  app transactions                     3333 non-null   int64
 17  add to cart per session              3333 non-null   float64
 18  customer service calls               3274 non-null   float64
 19  churn                                3333 non-null   int64
dtypes: float64(6), int64(12), object(2)
memory usage: 520.9+ KB

In [7]:
# Null Values

In [8]:
n=df.isna().sum()

In [9]:
n[n>0]

total product detail views             52
product detail view per app session    61
customer service calls                 59
dtype: int64

In [10]:
# Unique Values

In [11]:
N=df.nunique()

In [12]:
N[N>1000]

user id            3333
avg order value    1591
dtype: int64

In [13]:
df.drop(['user id'],axis=1,inplace=True)     #remove discrete column

In [14]:
# Seperate target column

In [15]:
x=df.drop(['churn'],axis=1)
y=df['churn']

# Preprocessing

In [16]:
for i in x.columns:
    if x[i].dtypes=='object':
        x[i]=x[i].fillna(x[i].mode()[0])
    else:
         x[i]=x[i].fillna(x[i].median())

In [17]:
x.isna().sum()

account length                         0
location code                          0
credit card info save                  0
push status                            0
add to wishlist                        0
desktop sessions                       0
app sessions                           0
desktop transactions                   0
total product detail views             0
session duration                       0
promotion clicks                       0
avg order value                        0
sale product views                     0
discount rate per visited products     0
product detail view per app session    0
app transactions                       0
add to cart per session                0
customer service calls                 0
dtype: int64

In [18]:
# Seperate features

In [19]:
x_cat=x.select_dtypes(include='object')
x_con=x.select_dtypes(exclude='object')

In [20]:
x_cat

     credit card info save push status
0                       no         yes
1                       no         yes
2                       no          no
3                      yes          no
4                      yes          no
...                    ...         ...
3328                    no         yes
3329                    no          no
3330                    no          no
3331                   yes          no
3332                    no         yes

[3333 rows x 2 columns]

In [21]:
x_con

,account length,location code,add to wishlist,desktop sessions,app sessions,desktop transactions,total product detail views,session duration,promotion clicks,avg order value,sale product views,discount rate per visited products,product detail view per app session,app transactions,add to cart per session,customer service calls
0,128,415,25,265,45,17,110.0,197,87,244.7,91,11.01,10.0,3,2.70,1.0
1,107,415,26,162,27,17,123.0,196,103,254.4,103,11.45,13.7,3,3.70,1.0
2,137,415,0,243,41,10,114.0,121,110,162.6,104,7.32,12.2,5,3.29,0.0
3,84,408,0,299,51,5,71.0,62,88,196.9,89,8.86,6.6,7,1.78,2.0
4,75,415,0,167,28,13,113.0,148,122,186.9,121,8.41,10.1,3,2.73,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,192,415,36,156,27,18,77.0,216,126,279.1,83,12.56,9.9,6,2.67,2.0
3329,68,415,0,231,39,13,101.0,153,55,191.3,123,8.61,9.6,4,2.59,3.0
3330,28,510,0,181,31,25,109.0,289,58,191.9,91,8.64,14.1,6,3.81,2.0
3331,184,510,0,214,36,14,105.0,160,84,139.2,137,6.26,5.0,10,1.35,2.0
3332,74,415,25,234,40,23,113.0,266,82,241.4,77,10.86,13.7,4,3.70,0.0

# Feature Selection

In [22]:
# Encoding

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
le=LabelEncoder()

In [25]:
x_cat=x_cat.apply(le.fit_transform)   #label encoding
x_cat

      credit card info save  push status
0                         0            1
1                         0            1
2                         0            0
3                         1            0
4                         1            0
...                     ...          ...
3328                      0            1
3329                      0            0
3330                      0            0
3331                      1            0
3332                      0            1

[3333 rows x 2 columns]

In [26]:
# Scaling

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
ss=StandardScaler()

In [29]:
x_con=pd.DataFrame(ss.fit_transform(x_con),columns=ss.get_feature_names_out())
x_con

,account length,location code,add to wishlist,desktop sessions,app sessions,desktop transactions,total product detail views,session duration,promotion clicks,avg order value,sale product views,discount rate per visited products,product detail view per app session,app transactions,add to cart per session,customer service calls
0,0.676489,-0.523603,1.234883,1.564550,1.557193,-0.020265,0.474708,-0.079666,-0.658138,0.866743,-0.465494,0.866029,-0.088435,-0.601195,-0.085690,-0.421808
1,0.149065,-0.523603,1.307948,-0.327130,-0.384977,-0.020265,1.128760,-0.099387,0.145038,1.058571,0.147825,1.059390,1.248892,-0.601195,1.241169,-0.421808
2,0.902529,-0.523603,-0.591760,1.160502,1.125600,-1.639456,0.675955,-1.578480,0.496427,-0.756869,0.198935,-0.755571,0.706732,0.211534,0.697156,-1.187125
3,-0.428590,-0.688834,-0.591760,2.188988,2.204583,-2.796021,-1.487447,-2.742033,-0.607939,-0.078551,-0.567714,-0.078806,-1.317330,1.024263,-1.306401,0.343509
4,-0.654629,-0.523603,-0.591760,-0.235301,-0.277078,-0.945517,0.625643,-1.046007,1.098809,-0.276311,1.067803,-0.276562,-0.052291,-0.601195,-0.045885,1.108826
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,2.283878,-0.523603,2.038605,-0.437325,-0.384977,0.211048,-1.185577,0.295038,1.299603,1.547039,-0.874374,1.547188,-0.124579,0.617898,-0.125496,0.343509
3329,-0.830437,-0.523603,-0.591760,0.940112,0.909803,-0.945517,0.021903,-0.947401,-2.264489,-0.189297,1.170023,-0.188670,-0.233011,-0.194831,-0.231645,1.108826
3330,-1.835055,1.718817,-0.591760,0.021821,0.046617,1.830239,0.424396,1.734688,-2.113894,-0.177431,-0.465494,-0.175486,1.393468,0.617898,1.387123,0.343509
3331,2.082955,1.718817,-0.591760,0.627893,0.586108,-0.714204,0.223150,-0.809352,-0.808733,-1.219628,1.885562,-1.221396,-1.895634,2.243356,-1.876950,0.343509
3332,-0.679745,-0.523603,1.234883,0.995209,1.017702,1.367613,0.625643,1.281100,-0.909130,0.801482,-1.181033,0.800110,1.248892,-0.194831,1.241169,-1.187125

# Combine categorical and continuous data

In [30]:
x1=x_con.join(x_cat)

In [31]:
x1

,account length,location code,add to wishlist,desktop sessions,app sessions,desktop transactions,total product detail views,session duration,promotion clicks,avg order value,sale product views,discount rate per visited products,product detail view per app session,app transactions,add to cart per session,customer service calls,credit card info save,push status
0,0.676489,-0.523603,1.234883,1.564550,1.557193,-0.020265,0.474708,-0.079666,-0.658138,0.866743,-0.465494,0.866029,-0.088435,-0.601195,-0.085690,-0.421808,0,1
1,0.149065,-0.523603,1.307948,-0.327130,-0.384977,-0.020265,1.128760,-0.099387,0.145038,1.058571,0.147825,1.059390,1.248892,-0.601195,1.241169,-0.421808,0,1
2,0.902529,-0.523603,-0.591760,1.160502,1.125600,-1.639456,0.675955,-1.578480,0.496427,-0.756869,0.198935,-0.755571,0.706732,0.211534,0.697156,-1.187125,0,0
3,-0.428590,-0.688834,-0.591760,2.188988,2.204583,-2.796021,-1.487447,-2.742033,-0.607939,-0.078551,-0.567714,-0.078806,-1.317330,1.024263,-1.306401,0.343509,1,0
4,-0.654629,-0.523603,-0.591760,-0.235301,-0.277078,-0.945517,0.625643,-1.046007,1.098809,-0.276311,1.067803,-0.276562,-0.052291,-0.601195,-0.045885,1.108826,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,2.283878,-0.523603,2.038605,-0.437325,-0.384977,0.211048,-1.185577,0.295038,1.299603,1.547039,-0.874374,1.547188,-0.124579,0.617898,-0.125496,0.343509,0,1
3329,-0.830437,-0.523603,-0.591760,0.940112,0.909803,-0.945517,0.021903,-0.947401,-2.264489,-0.189297,1.170023,-0.188670,-0.233011,-0.194831,-0.231645,1.108826,0,0
3330,-1.835055,1.718817,-0.591760,0.021821,0.046617,1.830239,0.424396,1.734688,-2.113894,-0.177431,-0.465494,-0.175486,1.393468,0.617898,1.387123,0.343509,0,0
3331,2.082955,1.718817,-0.591760,0.627893,0.586108,-0.714204,0.223150,-0.809352,-0.808733,-1.219628,1.885562,-1.221396,-1.895634,2.243356,-1.876950,0.343509,1,0
3332,-0.679745,-0.523603,1.234883,0.995209,1.017702,1.367613,0.625643,1.281100,-0.909130,0.801482,-1.181033,0.800110,1.248892,-0.194831,1.241169,-1.187125,0,1

In [32]:
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LinearRegression

In [33]:
lr=LinearRegression()

In [34]:
sfs=SequentialFeatureSelector(lr)
sfs.fit_transform(x1,y)

array([[ 1.56454983,  1.55719319, -0.079666  , ..., -0.42180839,
         0.        ,  1.        ],
       [-0.32712984, -0.38497654, -0.09938724, ..., -0.42180839,
         0.        ,  1.        ],
       [ 1.16050174,  1.12559992, -1.57848024, ..., -1.18712541,
         0.        ,  0.        ],
       ...,
       [ 0.02182078,  0.04661674,  1.73468809, ...,  0.34350863,
         0.        ,  0.        ],
       [ 0.62789291,  0.58610833, -0.80935188, ...,  0.34350863,
         1.        ,  0.        ],
       [ 0.99520935,  1.0177016 ,  1.28109956, ..., -1.18712541,
         0.        ,  1.        ]])

In [35]:
cols=sfs.get_feature_names_out()   #list of columns selected by using feature selector.
cols

array(['desktop sessions', 'app sessions', 'session duration',
       'discount rate per visited products',
       'product detail view per app session', 'app transactions',
       'customer service calls', 'credit card info save', 'push status'],
      dtype=object)

In [36]:
x2=pd.DataFrame(x,columns=cols)   #select the important feature from main dataset by using list of imp column

In [37]:
x2

,desktop sessions,app sessions,session duration,discount rate per visited products,product detail view per app session,app transactions,customer service calls,credit card info save,push status
0,265,45,197,11.01,10.0,3,1.0,no,yes
1,162,27,196,11.45,13.7,3,1.0,no,yes
2,243,41,121,7.32,12.2,5,0.0,no,no
3,299,51,62,8.86,6.6,7,2.0,yes,no
4,167,28,148,8.41,10.1,3,3.0,yes,no
...,...,...,...,...,...,...,...,...,...
3328,156,27,216,12.56,9.9,6,2.0,no,yes
3329,231,39,153,8.61,9.6,4,3.0,no,no
3330,181,31,289,8.64,14.1,6,2.0,no,no
3331,214,36,160,6.26,5.0,10,2.0,yes,no
3332,234,40,266,10.86,13.7,4,0.0,no,yes

# Preprocessing by usning sklearn Pipeline

In [38]:
cat=[]
con=[]

for i in x2.columns:
    if x2[i].dtypes=='object':
        cat.append(i)
    else:
        con.append(i)

In [39]:
cat

['credit card info save', 'push status']

In [40]:
#import libraries for pipeline

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [41]:
# Numerical Pipeline
num_pipeline = Pipeline(steps=[('imputer',SimpleImputer(strategy='mean')),
                               ('scaler',StandardScaler())])

# Categorical Pipeline
cat_pipeline = Pipeline(steps=[('imputer',SimpleImputer(strategy='most_frequent')),
                               ('ord_enc',OrdinalEncoder())])

# Combine pipelines using Column Transformer
pre = ColumnTransformer([('num',num_pipeline,con),
                         ('cat',cat_pipeline,cat)])

In [42]:
x3=pre.fit_transform(x2)
x3

array([[ 1.56454983,  1.55719319, -0.079666  , ..., -0.42180839,
         0.        ,  1.        ],
       [-0.32712984, -0.38497654, -0.09938724, ..., -0.42180839,
         0.        ,  1.        ],
       [ 1.16050174,  1.12559992, -1.57848024, ..., -1.18712541,
         0.        ,  0.        ],
       ...,
       [ 0.02182078,  0.04661674,  1.73468809, ...,  0.34350863,
         0.        ,  0.        ],
       [ 0.62789291,  0.58610833, -0.80935188, ...,  0.34350863,
         1.        ,  0.        ],
       [ 0.99520935,  1.0177016 ,  1.28109956, ..., -1.18712541,
         0.        ,  1.        ]])

In [43]:
cols1=pre.get_feature_names_out()
cols1

array(['num__desktop sessions', 'num__app sessions',
       'num__session duration', 'num__discount rate per visited products',
       'num__product detail view per app session',
       'num__app transactions', 'num__customer service calls',
       'cat__credit card info save', 'cat__push status'], dtype=object)

In [44]:
x3=pd.DataFrame(x3,columns=cols1)    #preprocess data after pipeline
x3

,num__desktop sessions,num__app sessions,num__session duration,num__discount rate per visited products,num__product detail view per app session,num__app transactions,num__customer service calls,cat__credit card info save,cat__push status
0,1.564550,1.557193,-0.079666,0.866029,-0.088435,-0.601195,-0.421808,0.0,1.0
1,-0.327130,-0.384977,-0.099387,1.059390,1.248892,-0.601195,-0.421808,0.0,1.0
2,1.160502,1.125600,-1.578480,-0.755571,0.706732,0.211534,-1.187125,0.0,0.0
3,2.188988,2.204583,-2.742033,-0.078806,-1.317330,1.024263,0.343509,1.0,0.0
4,-0.235301,-0.277078,-1.046007,-0.276562,-0.052291,-0.601195,1.108826,1.0,0.0
...,...,...,...,...,...,...,...,...,...
3328,-0.437325,-0.384977,0.295038,1.547188,-0.124579,0.617898,0.343509,0.0,1.0
3329,0.940112,0.909803,-0.947401,-0.188670,-0.233011,-0.194831,1.108826,0.0,0.0
3330,0.021821,0.046617,1.734688,-0.175486,1.393468,0.617898,0.343509,0.0,0.0
3331,0.627893,0.586108,-0.809352,-1.221396,-1.895634,2.243356,0.343509,1.0,0.0
3332,0.995209,1.017702,1.281100,0.800110,1.248892,-0.194831,-1.187125,0.0,1.0

# Create Training and Testing set

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
x_train,x_test,y_train,y_test=train_test_split(x3,y,test_size=0.2,random_state=21)

# Model Evaluation

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC

In [48]:
la=LogisticRegression()   
kn=KNeighborsClassifier()
dt=DecisionTreeClassifier()
rf=RandomForestClassifier()
ab=AdaBoostClassifier()
sv=SVC()

In [49]:
list1=[la,kn,dt,rf,ab,sv]

In [50]:
for i in list1:                                   #check all model at once
    i.fit(x_train,y_train)                        #fit all model from list
    y_pred=i.predict(x_test)
    from sklearn.metrics import f1_score
    ts_f1 = f1_score(y_pred,y_test)
    
    
    print('__'*20)
    print('Model:',i)
    print('f1_score:',ts_f1)

________________________________________
Model: LogisticRegression()
f1_score: 0.3829787234042553
________________________________________
Model: KNeighborsClassifier()
f1_score: 0.5526315789473684
________________________________________
Model: DecisionTreeClassifier()
f1_score: 0.732394366197183
________________________________________
Model: RandomForestClassifier()
f1_score: 0.8449197860962566
________________________________________
Model: AdaBoostClassifier()
f1_score: 0.4102564102564103
________________________________________
Model: SVC()
f1_score: 0.6783625730994153

# Hyperparameter Tuning

In [51]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
import numpy as np

In [52]:
grid={
    'n_estimators':range(1,300),
    
    'criterion':['gini','entropy'],
    'max_depth':range(1,50),
    'min_samples_split':range(1,10),
    'min_samples_leaf':range(1,10)
}

In [53]:
grid

{'n_estimators': range(1, 300),
 'criterion': ['gini', 'entropy'],
 'max_depth': range(1, 50),
 'min_samples_split': range(1, 10),
 'min_samples_leaf': range(1, 10)}

In [54]:
gs=RandomizedSearchCV(rf,grid,cv=4)

In [55]:
gs.fit(x_train,y_train)

RandomizedSearchCV(cv=4, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': range(1, 50),
                                        'min_samples_leaf': range(1, 10),
                                        'min_samples_split': range(1, 10),
                                        'n_estimators': range(1, 300)})

In [56]:
gs.best_params_

{'n_estimators': 129,
 'min_samples_split': 9,
 'min_samples_leaf': 1,
 'max_depth': 49,
 'criterion': 'gini'}

# Final Model

In [57]:
rf=RandomForestClassifier(n_estimators=168,min_samples_split=7,min_samples_leaf=4,max_depth=47,criterion='gini')

In [58]:
rf.fit(x_train,y_train)

RandomForestClassifier(max_depth=47, min_samples_leaf=4, min_samples_split=7,
                       n_estimators=168)

# Evaluation

In [59]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

# Training Data Evaluation

In [60]:
y_pred_train=rf.predict(x_train)

print('__'*30)
acc=accuracy_score(y_pred_train,y_train)
print('Accuracy:',acc)

print('__'*30)

cnf=confusion_matrix(y_pred_train,y_train)
print('Confusion_matrix:\n',cnf)

print('__'*30)

clf=classification_report(y_pred_train,y_train)
print('classification report:\n',clf)

print('__'*30)

____________________________________________________________
Accuracy: 0.9752438109527382
____________________________________________________________
Confusion_matrix:
 [[2287   65]
 [   1  313]]
____________________________________________________________
classification report:
               precision    recall  f1-score   support

           0       1.00      0.97      0.99      2352
           1       0.83      1.00      0.90       314

    accuracy                           0.98      2666
   macro avg       0.91      0.98      0.95      2666
weighted avg       0.98      0.98      0.98      2666

____________________________________________________________

# Testing Data Evaluation

In [ ]:
y_pred=rf.predict(x_test)

print('__'*30)
acc1=accuracy_score(y_pred,y_test)
print('Accuracy:',acc1)

print('__'*30)

cnf1=confusion_matrix(y_pred,y_test)
print('Confusion_matrix:\n',cnf1)

print('__'*30)

clf1=classification_report(y_pred,y_test)
print('classification report:\n',clf1)

print('__'*30)

# Import Unseen data

In [61]:
df2=pd.read_csv('testing_ecommerce.csv')
df2

,account length,location code,user id,credit card info save,push status,add to wishlist,desktop sessions,app sessions,desktop transactions,total product detail views,session duration,promotion clicks,avg order value,sale product views,discount rate per visited products,product detail view per app session,app transactions,add to cart per session,customer service calls
0,116,415,3802929,no,yes,24,233,40,13,90.0,152,94,344.3,82,15.49,10.7,6,2.89,1.0
1,56,415,3895988,no,yes,24,122,21,16,87.0,184,76,266.6,98,12.00,12.7,3,3.43,1.0
2,122,415,4067737,yes,yes,40,216,37,21,80.0,250,90,185.9,99,8.37,12.7,4,3.43,1.0
3,76,510,4218141,no,no,0,166,28,22,94.0,257,80,170.8,114,7.69,10.0,4,2.70,1.0
4,85,510,4042871,no,no,0,183,31,14,111.0,169,98,199.7,97,8.99,9.9,4,2.67,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,408,3312144,no,yes,26,208,35,16,115.0,185,113,177.7,144,8.00,8.1,9,2.19,1.0
996,137,408,3573187,no,no,0,209,36,19,120.0,225,100,221.6,130,9.97,11.1,5,3.00,0.0
997,96,510,4205990,no,no,0,98,17,26,100.0,307,88,182.5,120,8.21,7.6,1,2.05,2.0
998,201,510,3738900,no,no,0,213,36,19,72.0,225,90,195.1,99,8.78,7.0,6,1.89,1.0
999,57,415,3485728,no,no,0,273,46,19,74.0,225,85,178.2,104,8.02,10.5,3,2.84,2.0

In [62]:
x_t=pre.transform(df2)       #transfrom the new data using preprocessing pipeline
x_t

array([[ 0.97684352,  1.0177016 , -0.9671218 , ..., -0.42180839,
         0.        ,  1.        ],
       [-1.06176272, -1.03236645, -0.33604212, ..., -0.42180839,
         0.        ,  1.        ],
       [ 0.66462455,  0.69400664,  0.96555972, ..., -0.42180839,
         1.        ,  1.        ],
       ...,
       [-1.50254245, -1.46395972,  2.08967041, ...,  0.34350863,
         0.        ,  0.        ],
       [ 0.60952708,  0.58610833,  0.47252872, ..., -0.42180839,
         0.        ,  0.        ],
       [ 1.71147641,  1.66509151,  0.47252872, ...,  0.34350863,
         0.        ,  0.        ]])

In [63]:
x_new=pd.DataFrame(x_t,columns=pre.get_feature_names_out())
x_new

,num__desktop sessions,num__app sessions,num__session duration,num__discount rate per visited products,num__product detail view per app session,num__app transactions,num__customer service calls,cat__credit card info save,cat__push status
0,0.976844,1.017702,-0.967122,2.834799,0.164573,0.617898,-0.421808,0.0,1.0
1,-1.061763,-1.032366,-0.336042,1.301092,0.887452,-0.601195,-0.421808,0.0,1.0
2,0.664625,0.694007,0.965560,-0.294140,0.887452,-0.194831,-0.421808,1.0,1.0
3,-0.253667,-0.277078,1.103608,-0.592971,-0.088435,-0.194831,-0.421808,0.0,0.0
4,0.058552,0.046617,-0.631861,-0.021676,-0.124579,-0.194831,1.874143,0.0,0.0
...,...,...,...,...,...,...,...,...,...
995,0.517698,0.478210,-0.316321,-0.456739,-0.775171,1.836992,-0.421808,0.0,1.0
996,0.536064,0.586108,0.472529,0.408992,0.309149,0.211534,-1.187125,0.0,0.0
997,-1.502542,-1.463960,2.089670,-0.364453,-0.955890,-1.413924,0.343509,0.0,0.0
998,0.609527,0.586108,0.472529,-0.113962,-1.172754,0.617898,-0.421808,0.0,0.0
999,1.711476,1.665092,0.472529,-0.447950,0.092285,-0.601195,0.343509,0.0,0.0

# Prediction on unseen data

In [69]:
predict1=rf.predict(x_new)

In [70]:
predict1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [71]:
prediction=df2[['user id']]                          #create new dataframe which contain Id column from df2

In [72]:
prediction['Predicted_Churn_status']=predict1        #store our prediction into this dataframe with name Predicted_sale_price

In [73]:
prediction

     user id  Predicted_Churn_status
0    3802929                       0
1    3895988                       0
2    4067737                       0
3    4218141                       0
4    4042871                       0
..       ...                     ...
995  3312144                       0
996  3573187                       0
997  4205990                       0
998  3738900                       0
999  3485728                       1

[1000 rows x 2 columns]